name: Create Release


# name: Main

# on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Build
#         run: echo ${{ github.sha }} > Release.txt
#       - name: Test
#         run: cat Release.txt
#       - name: Release
#         uses: softprops/action-gh-release@v2
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           files: Release.txt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_release:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          profile: minimal

      - name: Build Release
        run: cargo build --release

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Executable
        # uses: actions/upload-release-asset@v1
        # with:
        #   upload_url: ${{ steps.create_release.outputs.upload_url }}
        #   asset_path: ./target/release/easy_project_finder.exe
        #   asset_name: easy_project_finder.exe
        #   asset_content_type: application/octet-stream

      - name: Upload Executable
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/easy_project_finder.exe